CREATE DATABASE stockora
    WITH ENCODING 'UTF8'
         TEMPLATE = template0;


SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_auditlog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_auditlog (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    model_name character varying(100) NOT NULL,
    object_id character varying(50) NOT NULL,
    object_repr character varying(200) NOT NULL,
    changes jsonb NOT NULL,
    ip_address inet,
    "timestamp" timestamp with time zone NOT NULL,
    user_id bigint
);


--
-- Name: accounts_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    phone character varying(20) NOT NULL,
    avatar character varying(100),
    company character varying(100) NOT NULL,
    is_active boolean NOT NULL
);


--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: django_site; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_inventorycount; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_inventorycount (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    status character varying(20) NOT NULL,
    notes text NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    warehouse_id bigint NOT NULL
);


--
-- Name: inventory_inventorycount_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_inventorycount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inventorycount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_inventorycountline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_inventorycountline (
    id bigint NOT NULL,
    system_quantity integer NOT NULL,
    counted_quantity integer,
    count_id bigint NOT NULL,
    product_id bigint NOT NULL,
    location_id bigint
);


--
-- Name: inventory_inventorycountline_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_inventorycountline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inventorycountline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_location; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_location (
    id bigint NOT NULL,
    aisle character varying(20) NOT NULL,
    shelf character varying(20) NOT NULL,
    level character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    warehouse_id bigint NOT NULL
);


--
-- Name: inventory_location_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_stockitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_stockitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    reserved_quantity integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    location_id bigint,
    product_id bigint NOT NULL,
    warehouse_id bigint NOT NULL
);


--
-- Name: inventory_stockitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_stockitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_stockitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_stockmovement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_stockmovement (
    id bigint NOT NULL,
    movement_type character varying(20) NOT NULL,
    quantity integer NOT NULL,
    unit_cost numeric(14,2) NOT NULL,
    reference character varying(200) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    batch_id bigint,
    from_location_id bigint,
    performed_by_id bigint,
    product_id bigint NOT NULL,
    serial_number_id bigint,
    to_location_id bigint,
    from_warehouse_id bigint,
    to_warehouse_id bigint
);


--
-- Name: inventory_stockmovement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_stockmovement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_stockmovement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_warehouse; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_warehouse (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    code character varying(20) NOT NULL,
    address text NOT NULL,
    phone character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    manager_id bigint
);


--
-- Name: inventory_warehouse_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_warehouse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_warehouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications_notification (
    id bigint NOT NULL,
    notification_type character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    link character varying(300) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications_stockalert; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications_stockalert (
    id bigint NOT NULL,
    current_quantity integer NOT NULL,
    threshold integer NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    product_id bigint NOT NULL,
    warehouse_id bigint NOT NULL
);


--
-- Name: notifications_stockalert_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications_stockalert ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_stockalert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_batch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_batch (
    id bigint NOT NULL,
    batch_number character varying(100) NOT NULL,
    manufacture_date date,
    expiry_date date,
    quantity integer NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: products_batch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    description text NOT NULL,
    icon character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    parent_id bigint
);


--
-- Name: products_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    sku character varying(100) NOT NULL,
    barcode character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    description text NOT NULL,
    image character varying(100),
    cost_price numeric(14,2) NOT NULL,
    sale_price numeric(14,2) NOT NULL,
    tax_rate numeric(5,2) NOT NULL,
    unit character varying(10) NOT NULL,
    min_stock integer NOT NULL,
    max_stock integer NOT NULL,
    reorder_point integer NOT NULL,
    reorder_quantity integer NOT NULL,
    has_batches boolean NOT NULL,
    has_serial_numbers boolean NOT NULL,
    valuation_method character varying(10) NOT NULL,
    is_active boolean NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    created_by_id bigint,
    CONSTRAINT products_product_max_stock_check CHECK ((max_stock >= 0)),
    CONSTRAINT products_product_min_stock_check CHECK ((min_stock >= 0)),
    CONSTRAINT products_product_reorder_point_check CHECK ((reorder_point >= 0)),
    CONSTRAINT products_product_reorder_quantity_check CHECK ((reorder_quantity >= 0))
);


--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_serialnumber; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_serialnumber (
    id bigint NOT NULL,
    serial character varying(200) NOT NULL,
    status character varying(20) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: products_serialnumber_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_serialnumber ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_serialnumber_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_customer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_customer (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(30) NOT NULL,
    address text NOT NULL,
    tax_id character varying(50) NOT NULL,
    notes text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: sales_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_quotation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_quotation (
    id bigint NOT NULL,
    quotation_number character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    valid_until date,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    customer_id bigint NOT NULL
);


--
-- Name: sales_quotation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_quotation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_quotation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_quotationitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_quotationitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(14,2) NOT NULL,
    discount numeric(14,2) NOT NULL,
    product_id bigint NOT NULL,
    quotation_id bigint NOT NULL,
    CONSTRAINT sales_quotationitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: sales_quotationitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_quotationitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_quotationitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_return; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_return (
    id bigint NOT NULL,
    reason text NOT NULL,
    restock boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    processed_by_id bigint,
    sale_id bigint NOT NULL
);


--
-- Name: sales_return_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_return ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_return_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_returnitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_returnitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    notes text NOT NULL,
    product_id bigint NOT NULL,
    return_order_id bigint NOT NULL,
    CONSTRAINT sales_returnitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: sales_returnitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_returnitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_returnitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_sale; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_sale (
    id bigint NOT NULL,
    invoice_number character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    payment_method character varying(20) NOT NULL,
    discount numeric(14,2) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    customer_id bigint,
    sold_by_id bigint,
    warehouse_id bigint NOT NULL
);


--
-- Name: sales_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_sale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_saleitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales_saleitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(14,2) NOT NULL,
    discount numeric(14,2) NOT NULL,
    tax_rate numeric(5,2) NOT NULL,
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL,
    CONSTRAINT sales_saleitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: sales_saleitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_saleitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_saleitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers_purchaseorder; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suppliers_purchaseorder (
    id bigint NOT NULL,
    order_number character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    expected_date date,
    received_date date,
    notes text NOT NULL,
    is_auto_generated boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    supplier_id bigint NOT NULL
);


--
-- Name: suppliers_purchaseorder_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suppliers_purchaseorder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_purchaseorder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers_purchaseorderitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suppliers_purchaseorderitem (
    id bigint NOT NULL,
    quantity_ordered integer NOT NULL,
    quantity_received integer NOT NULL,
    unit_cost numeric(14,2) NOT NULL,
    notes text NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT suppliers_purchaseorderitem_quantity_ordered_check CHECK ((quantity_ordered >= 0)),
    CONSTRAINT suppliers_purchaseorderitem_quantity_received_check CHECK ((quantity_received >= 0))
);


--
-- Name: suppliers_purchaseorderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suppliers_purchaseorderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_purchaseorderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers_supplier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suppliers_supplier (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    contact_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(30) NOT NULL,
    address text NOT NULL,
    tax_id character varying(50) NOT NULL,
    website character varying(200) NOT NULL,
    notes text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: suppliers_supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suppliers_supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers_supplierproduct; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.suppliers_supplierproduct (
    id bigint NOT NULL,
    supplier_sku character varying(100) NOT NULL,
    cost_price numeric(14,2) NOT NULL,
    lead_time_days integer NOT NULL,
    min_order_quantity integer NOT NULL,
    is_preferred boolean NOT NULL,
    product_id bigint NOT NULL,
    supplier_id bigint NOT NULL,
    CONSTRAINT suppliers_supplierproduct_lead_time_days_check CHECK ((lead_time_days >= 0)),
    CONSTRAINT suppliers_supplierproduct_min_order_quantity_check CHECK ((min_order_quantity >= 0))
);


--
-- Name: suppliers_supplierproduct_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.suppliers_supplierproduct ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_supplierproduct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: accounts_auditlog accounts_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_auditlog
    ADD CONSTRAINT accounts_auditlog_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: inventory_inventorycount inventory_inventorycount_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_inventorycount
    ADD CONSTRAINT inventory_inventorycount_pkey PRIMARY KEY (id);


--
-- Name: inventory_inventorycountline inventory_inventorycountline_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_inventorycountline
    ADD CONSTRAINT inventory_inventorycountline_pkey PRIMARY KEY (id);


--
-- Name: inventory_location inventory_location_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_location
    ADD CONSTRAINT inventory_location_pkey PRIMARY KEY (id);


--
-- Name: inventory_location inventory_location_warehouse_id_aisle_shelf_level_64b01c8e_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_location
    ADD CONSTRAINT inventory_location_warehouse_id_aisle_shelf_level_64b01c8e_uniq UNIQUE (warehouse_id, aisle, shelf, level);


--
-- Name: inventory_stockitem inventory_stockitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockitem
    ADD CONSTRAINT inventory_stockitem_pkey PRIMARY KEY (id);


--
-- Name: inventory_stockitem inventory_stockitem_product_id_warehouse_id__d84c94dc_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockitem
    ADD CONSTRAINT inventory_stockitem_product_id_warehouse_id__d84c94dc_uniq UNIQUE (product_id, warehouse_id, location_id);


--
-- Name: inventory_stockmovement inventory_stockmovement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovement_pkey PRIMARY KEY (id);


--
-- Name: inventory_warehouse inventory_warehouse_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_warehouse
    ADD CONSTRAINT inventory_warehouse_code_key UNIQUE (code);


--
-- Name: inventory_warehouse inventory_warehouse_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_warehouse
    ADD CONSTRAINT inventory_warehouse_pkey PRIMARY KEY (id);


--
-- Name: notifications_notification notifications_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_pkey PRIMARY KEY (id);


--
-- Name: notifications_stockalert notifications_stockalert_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_stockalert
    ADD CONSTRAINT notifications_stockalert_pkey PRIMARY KEY (id);


--
-- Name: notifications_stockalert notifications_stockalert_product_id_warehouse_id__7c548d65_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_stockalert
    ADD CONSTRAINT notifications_stockalert_product_id_warehouse_id__7c548d65_uniq UNIQUE (product_id, warehouse_id, status);


--
-- Name: products_batch products_batch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_batch
    ADD CONSTRAINT products_batch_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_name_key UNIQUE (name);


--
-- Name: products_category products_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_slug_key UNIQUE (slug);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_sku_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_sku_key UNIQUE (sku);


--
-- Name: products_product products_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_slug_key UNIQUE (slug);


--
-- Name: products_serialnumber products_serialnumber_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_serialnumber
    ADD CONSTRAINT products_serialnumber_pkey PRIMARY KEY (id);


--
-- Name: products_serialnumber products_serialnumber_serial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_serialnumber
    ADD CONSTRAINT products_serialnumber_serial_key UNIQUE (serial);


--
-- Name: sales_customer sales_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_customer
    ADD CONSTRAINT sales_customer_pkey PRIMARY KEY (id);


--
-- Name: sales_quotation sales_quotation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_quotation
    ADD CONSTRAINT sales_quotation_pkey PRIMARY KEY (id);


--
-- Name: sales_quotation sales_quotation_quotation_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_quotation
    ADD CONSTRAINT sales_quotation_quotation_number_key UNIQUE (quotation_number);


--
-- Name: sales_quotationitem sales_quotationitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_quotationitem
    ADD CONSTRAINT sales_quotationitem_pkey PRIMARY KEY (id);


--
-- Name: sales_return sales_return_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_return
    ADD CONSTRAINT sales_return_pkey PRIMARY KEY (id);


--
-- Name: sales_returnitem sales_returnitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_returnitem
    ADD CONSTRAINT sales_returnitem_pkey PRIMARY KEY (id);


--
-- Name: sales_sale sales_sale_invoice_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_invoice_number_key UNIQUE (invoice_number);


--
-- Name: sales_sale sales_sale_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_pkey PRIMARY KEY (id);


--
-- Name: sales_saleitem sales_saleitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_pkey PRIMARY KEY (id);


--
-- Name: suppliers_purchaseorder suppliers_purchaseorder_order_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_purchaseorder
    ADD CONSTRAINT suppliers_purchaseorder_order_number_key UNIQUE (order_number);


--
-- Name: suppliers_purchaseorder suppliers_purchaseorder_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_purchaseorder
    ADD CONSTRAINT suppliers_purchaseorder_pkey PRIMARY KEY (id);


--
-- Name: suppliers_purchaseorderitem suppliers_purchaseorderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_purchaseorderitem
    ADD CONSTRAINT suppliers_purchaseorderitem_pkey PRIMARY KEY (id);


--
-- Name: suppliers_supplier suppliers_supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_supplier
    ADD CONSTRAINT suppliers_supplier_pkey PRIMARY KEY (id);


--
-- Name: suppliers_supplierproduct suppliers_supplierproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_supplierproduct
    ADD CONSTRAINT suppliers_supplierproduct_pkey PRIMARY KEY (id);


--
-- Name: suppliers_supplierproduct suppliers_supplierproduct_supplier_id_product_id_b01754ab_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_supplierproduct
    ADD CONSTRAINT suppliers_supplierproduct_supplier_id_product_id_b01754ab_uniq UNIQUE (supplier_id, product_id);


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: accounts_auditlog_user_id_1dfbca79; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_auditlog_user_id_1dfbca79 ON public.accounts_auditlog USING btree (user_id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: inventory_inventorycount_created_by_id_cebaf17b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_inventorycount_created_by_id_cebaf17b ON public.inventory_inventorycount USING btree (created_by_id);


--
-- Name: inventory_inventorycount_warehouse_id_402361fc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_inventorycount_warehouse_id_402361fc ON public.inventory_inventorycount USING btree (warehouse_id);


--
-- Name: inventory_inventorycountline_count_id_4c040969; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_inventorycountline_count_id_4c040969 ON public.inventory_inventorycountline USING btree (count_id);


--
-- Name: inventory_inventorycountline_location_id_869aa470; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_inventorycountline_location_id_869aa470 ON public.inventory_inventorycountline USING btree (location_id);


--
-- Name: inventory_inventorycountline_product_id_1255281f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_inventorycountline_product_id_1255281f ON public.inventory_inventorycountline USING btree (product_id);


--
-- Name: inventory_location_warehouse_id_972ee1ee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_location_warehouse_id_972ee1ee ON public.inventory_location USING btree (warehouse_id);


--
-- Name: inventory_stockitem_location_id_18093e41; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockitem_location_id_18093e41 ON public.inventory_stockitem USING btree (location_id);


--
-- Name: inventory_stockitem_product_id_90083cf4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockitem_product_id_90083cf4 ON public.inventory_stockitem USING btree (product_id);


--
-- Name: inventory_stockitem_warehouse_id_4607d99a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockitem_warehouse_id_4607d99a ON public.inventory_stockitem USING btree (warehouse_id);


--
-- Name: inventory_stockmovement_batch_id_8ca2b965; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockmovement_batch_id_8ca2b965 ON public.inventory_stockmovement USING btree (batch_id);


--
-- Name: inventory_stockmovement_from_location_id_fec5e827; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockmovement_from_location_id_fec5e827 ON public.inventory_stockmovement USING btree (from_location_id);


--
-- Name: inventory_stockmovement_from_warehouse_id_6ba809a0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockmovement_from_warehouse_id_6ba809a0 ON public.inventory_stockmovement USING btree (from_warehouse_id);


--
-- Name: inventory_stockmovement_performed_by_id_31c9b1d0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockmovement_performed_by_id_31c9b1d0 ON public.inventory_stockmovement USING btree (performed_by_id);


--
-- Name: inventory_stockmovement_product_id_4eccfd0a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockmovement_product_id_4eccfd0a ON public.inventory_stockmovement USING btree (product_id);


--
-- Name: inventory_stockmovement_serial_number_id_c7f675ab; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockmovement_serial_number_id_c7f675ab ON public.inventory_stockmovement USING btree (serial_number_id);


--
-- Name: inventory_stockmovement_to_location_id_6b5863ab; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockmovement_to_location_id_6b5863ab ON public.inventory_stockmovement USING btree (to_location_id);


--
-- Name: inventory_stockmovement_to_warehouse_id_a3872d26; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_stockmovement_to_warehouse_id_a3872d26 ON public.inventory_stockmovement USING btree (to_warehouse_id);


--
-- Name: inventory_warehouse_code_ad40093e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_warehouse_code_ad40093e_like ON public.inventory_warehouse USING btree (code varchar_pattern_ops);


--
-- Name: inventory_warehouse_manager_id_6def176a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX inventory_warehouse_manager_id_6def176a ON public.inventory_warehouse USING btree (manager_id);


--
-- Name: notifications_notification_user_id_b5e8c0ff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_notification_user_id_b5e8c0ff ON public.notifications_notification USING btree (user_id);


--
-- Name: notifications_stockalert_product_id_5f88c11d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_stockalert_product_id_5f88c11d ON public.notifications_stockalert USING btree (product_id);


--
-- Name: notifications_stockalert_warehouse_id_bd02df0f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notifications_stockalert_warehouse_id_bd02df0f ON public.notifications_stockalert USING btree (warehouse_id);


--
-- Name: products_batch_product_id_68d28a3d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_batch_product_id_68d28a3d ON public.products_batch USING btree (product_id);


--
-- Name: products_category_name_0ecfb368_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_category_name_0ecfb368_like ON public.products_category USING btree (name varchar_pattern_ops);


--
-- Name: products_category_parent_id_3388f6c9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_category_parent_id_3388f6c9 ON public.products_category USING btree (parent_id);


--
-- Name: products_category_slug_c558efae_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_category_slug_c558efae_like ON public.products_category USING btree (slug varchar_pattern_ops);


--
-- Name: products_product_barcode_0b42bc05; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_product_barcode_0b42bc05 ON public.products_product USING btree (barcode);


--
-- Name: products_product_barcode_0b42bc05_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_product_barcode_0b42bc05_like ON public.products_product USING btree (barcode varchar_pattern_ops);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_product_created_by_id_dd4af40e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_product_created_by_id_dd4af40e ON public.products_product USING btree (created_by_id);


--
-- Name: products_product_sku_3c51a516_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_product_sku_3c51a516_like ON public.products_product USING btree (sku varchar_pattern_ops);


--
-- Name: products_product_slug_70d3148d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_product_slug_70d3148d_like ON public.products_product USING btree (slug varchar_pattern_ops);


--
-- Name: products_serialnumber_product_id_37ff3657; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_serialnumber_product_id_37ff3657 ON public.products_serialnumber USING btree (product_id);


--
-- Name: products_serialnumber_serial_f111d68c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX products_serialnumber_serial_f111d68c_like ON public.products_serialnumber USING btree (serial varchar_pattern_ops);


--
-- Name: sales_quotation_created_by_id_5281fe31; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_quotation_created_by_id_5281fe31 ON public.sales_quotation USING btree (created_by_id);


--
-- Name: sales_quotation_customer_id_c1726d2a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_quotation_customer_id_c1726d2a ON public.sales_quotation USING btree (customer_id);


--
-- Name: sales_quotation_quotation_number_48ef0c38_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_quotation_quotation_number_48ef0c38_like ON public.sales_quotation USING btree (quotation_number varchar_pattern_ops);


--
-- Name: sales_quotationitem_product_id_ea4eb2cd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_quotationitem_product_id_ea4eb2cd ON public.sales_quotationitem USING btree (product_id);


--
-- Name: sales_quotationitem_quotation_id_5c195674; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_quotationitem_quotation_id_5c195674 ON public.sales_quotationitem USING btree (quotation_id);


--
-- Name: sales_return_processed_by_id_91388c0f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_return_processed_by_id_91388c0f ON public.sales_return USING btree (processed_by_id);


--
-- Name: sales_return_sale_id_a9510270; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_return_sale_id_a9510270 ON public.sales_return USING btree (sale_id);


--
-- Name: sales_returnitem_product_id_2fe1b661; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_returnitem_product_id_2fe1b661 ON public.sales_returnitem USING btree (product_id);


--
-- Name: sales_returnitem_return_order_id_3422ca5a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_returnitem_return_order_id_3422ca5a ON public.sales_returnitem USING btree (return_order_id);


--
-- Name: sales_sale_customer_id_2d66a408; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_sale_customer_id_2d66a408 ON public.sales_sale USING btree (customer_id);


--
-- Name: sales_sale_invoice_number_a14f1a3f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_sale_invoice_number_a14f1a3f_like ON public.sales_sale USING btree (invoice_number varchar_pattern_ops);


--
-- Name: sales_sale_sold_by_id_c69f0cbe; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_sale_sold_by_id_c69f0cbe ON public.sales_sale USING btree (sold_by_id);


--
-- Name: sales_sale_warehouse_id_1c879624; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_sale_warehouse_id_1c879624 ON public.sales_sale USING btree (warehouse_id);


--
-- Name: sales_saleitem_product_id_aeb6c9cd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_saleitem_product_id_aeb6c9cd ON public.sales_saleitem USING btree (product_id);


--
-- Name: sales_saleitem_sale_id_56e67045; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sales_saleitem_sale_id_56e67045 ON public.sales_saleitem USING btree (sale_id);


--
-- Name: suppliers_purchaseorder_created_by_id_2ea025f3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suppliers_purchaseorder_created_by_id_2ea025f3 ON public.suppliers_purchaseorder USING btree (created_by_id);


--
-- Name: suppliers_purchaseorder_order_number_63da533e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suppliers_purchaseorder_order_number_63da533e_like ON public.suppliers_purchaseorder USING btree (order_number varchar_pattern_ops);


--
-- Name: suppliers_purchaseorder_supplier_id_398b3921; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suppliers_purchaseorder_supplier_id_398b3921 ON public.suppliers_purchaseorder USING btree (supplier_id);


--
-- Name: suppliers_purchaseorderitem_order_id_f3ccb97e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suppliers_purchaseorderitem_order_id_f3ccb97e ON public.suppliers_purchaseorderitem USING btree (order_id);


--
-- Name: suppliers_purchaseorderitem_product_id_14c4e768; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suppliers_purchaseorderitem_product_id_14c4e768 ON public.suppliers_purchaseorderitem USING btree (product_id);


--
-- Name: suppliers_supplierproduct_product_id_dde39474; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suppliers_supplierproduct_product_id_dde39474 ON public.suppliers_supplierproduct USING btree (product_id);


--
-- Name: suppliers_supplierproduct_supplier_id_160dc6f9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX suppliers_supplierproduct_supplier_id_160dc6f9 ON public.suppliers_supplierproduct USING btree (supplier_id);


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_auditlog accounts_auditlog_user_id_1dfbca79_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_auditlog
    ADD CONSTRAINT accounts_auditlog_user_id_1dfbca79_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_inventorycountline inventory_inventoryc_count_id_4c040969_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_inventorycountline
    ADD CONSTRAINT inventory_inventoryc_count_id_4c040969_fk_inventory FOREIGN KEY (count_id) REFERENCES public.inventory_inventorycount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_inventorycount inventory_inventoryc_created_by_id_cebaf17b_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_inventorycount
    ADD CONSTRAINT inventory_inventoryc_created_by_id_cebaf17b_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_inventorycountline inventory_inventoryc_location_id_869aa470_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_inventorycountline
    ADD CONSTRAINT inventory_inventoryc_location_id_869aa470_fk_inventory FOREIGN KEY (location_id) REFERENCES public.inventory_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_inventorycountline inventory_inventoryc_product_id_1255281f_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_inventorycountline
    ADD CONSTRAINT inventory_inventoryc_product_id_1255281f_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_inventorycount inventory_inventoryc_warehouse_id_402361fc_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_inventorycount
    ADD CONSTRAINT inventory_inventoryc_warehouse_id_402361fc_fk_inventory FOREIGN KEY (warehouse_id) REFERENCES public.inventory_warehouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_location inventory_location_warehouse_id_972ee1ee_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_location
    ADD CONSTRAINT inventory_location_warehouse_id_972ee1ee_fk_inventory FOREIGN KEY (warehouse_id) REFERENCES public.inventory_warehouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockitem inventory_stockitem_location_id_18093e41_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockitem
    ADD CONSTRAINT inventory_stockitem_location_id_18093e41_fk_inventory FOREIGN KEY (location_id) REFERENCES public.inventory_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockitem inventory_stockitem_product_id_90083cf4_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockitem
    ADD CONSTRAINT inventory_stockitem_product_id_90083cf4_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockitem inventory_stockitem_warehouse_id_4607d99a_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockitem
    ADD CONSTRAINT inventory_stockitem_warehouse_id_4607d99a_fk_inventory FOREIGN KEY (warehouse_id) REFERENCES public.inventory_warehouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockmovement inventory_stockmovem_from_location_id_fec5e827_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovem_from_location_id_fec5e827_fk_inventory FOREIGN KEY (from_location_id) REFERENCES public.inventory_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockmovement inventory_stockmovem_from_warehouse_id_6ba809a0_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovem_from_warehouse_id_6ba809a0_fk_inventory FOREIGN KEY (from_warehouse_id) REFERENCES public.inventory_warehouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockmovement inventory_stockmovem_performed_by_id_31c9b1d0_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovem_performed_by_id_31c9b1d0_fk_accounts_ FOREIGN KEY (performed_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockmovement inventory_stockmovem_product_id_4eccfd0a_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovem_product_id_4eccfd0a_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockmovement inventory_stockmovem_serial_number_id_c7f675ab_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovem_serial_number_id_c7f675ab_fk_products_ FOREIGN KEY (serial_number_id) REFERENCES public.products_serialnumber(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockmovement inventory_stockmovem_to_location_id_6b5863ab_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovem_to_location_id_6b5863ab_fk_inventory FOREIGN KEY (to_location_id) REFERENCES public.inventory_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockmovement inventory_stockmovem_to_warehouse_id_a3872d26_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovem_to_warehouse_id_a3872d26_fk_inventory FOREIGN KEY (to_warehouse_id) REFERENCES public.inventory_warehouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_stockmovement inventory_stockmovement_batch_id_8ca2b965_fk_products_batch_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_stockmovement
    ADD CONSTRAINT inventory_stockmovement_batch_id_8ca2b965_fk_products_batch_id FOREIGN KEY (batch_id) REFERENCES public.products_batch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_warehouse inventory_warehouse_manager_id_6def176a_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_warehouse
    ADD CONSTRAINT inventory_warehouse_manager_id_6def176a_fk_accounts_user_id FOREIGN KEY (manager_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_notification notifications_notification_user_id_b5e8c0ff_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_user_id_b5e8c0ff_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_stockalert notifications_stocka_product_id_5f88c11d_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_stockalert
    ADD CONSTRAINT notifications_stocka_product_id_5f88c11d_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications_stockalert notifications_stocka_warehouse_id_bd02df0f_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications_stockalert
    ADD CONSTRAINT notifications_stocka_warehouse_id_bd02df0f_fk_inventory FOREIGN KEY (warehouse_id) REFERENCES public.inventory_warehouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_batch products_batch_product_id_68d28a3d_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_batch
    ADD CONSTRAINT products_batch_product_id_68d28a3d_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_category products_category_parent_id_3388f6c9_fk_products_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_parent_id_3388f6c9_fk_products_category_id FOREIGN KEY (parent_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_category_id_9b594869_fk_products_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_products_category_id FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_created_by_id_dd4af40e_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_created_by_id_dd4af40e_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_serialnumber products_serialnumbe_product_id_37ff3657_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_serialnumber
    ADD CONSTRAINT products_serialnumbe_product_id_37ff3657_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_quotation sales_quotation_created_by_id_5281fe31_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_quotation
    ADD CONSTRAINT sales_quotation_created_by_id_5281fe31_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_quotation sales_quotation_customer_id_c1726d2a_fk_sales_customer_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_quotation
    ADD CONSTRAINT sales_quotation_customer_id_c1726d2a_fk_sales_customer_id FOREIGN KEY (customer_id) REFERENCES public.sales_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_quotationitem sales_quotationitem_product_id_ea4eb2cd_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_quotationitem
    ADD CONSTRAINT sales_quotationitem_product_id_ea4eb2cd_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_quotationitem sales_quotationitem_quotation_id_5c195674_fk_sales_quotation_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_quotationitem
    ADD CONSTRAINT sales_quotationitem_quotation_id_5c195674_fk_sales_quotation_id FOREIGN KEY (quotation_id) REFERENCES public.sales_quotation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_return sales_return_processed_by_id_91388c0f_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_return
    ADD CONSTRAINT sales_return_processed_by_id_91388c0f_fk_accounts_user_id FOREIGN KEY (processed_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_return sales_return_sale_id_a9510270_fk_sales_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_return
    ADD CONSTRAINT sales_return_sale_id_a9510270_fk_sales_sale_id FOREIGN KEY (sale_id) REFERENCES public.sales_sale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_returnitem sales_returnitem_product_id_2fe1b661_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_returnitem
    ADD CONSTRAINT sales_returnitem_product_id_2fe1b661_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_returnitem sales_returnitem_return_order_id_3422ca5a_fk_sales_return_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_returnitem
    ADD CONSTRAINT sales_returnitem_return_order_id_3422ca5a_fk_sales_return_id FOREIGN KEY (return_order_id) REFERENCES public.sales_return(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_sale sales_sale_customer_id_2d66a408_fk_sales_customer_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_customer_id_2d66a408_fk_sales_customer_id FOREIGN KEY (customer_id) REFERENCES public.sales_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_sale sales_sale_sold_by_id_c69f0cbe_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_sold_by_id_c69f0cbe_fk_accounts_user_id FOREIGN KEY (sold_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_sale sales_sale_warehouse_id_1c879624_fk_inventory_warehouse_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_sale
    ADD CONSTRAINT sales_sale_warehouse_id_1c879624_fk_inventory_warehouse_id FOREIGN KEY (warehouse_id) REFERENCES public.inventory_warehouse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_saleitem sales_saleitem_product_id_aeb6c9cd_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_product_id_aeb6c9cd_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sales_saleitem sales_saleitem_sale_id_56e67045_fk_sales_sale_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_saleitem
    ADD CONSTRAINT sales_saleitem_sale_id_56e67045_fk_sales_sale_id FOREIGN KEY (sale_id) REFERENCES public.sales_sale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suppliers_purchaseorder suppliers_purchaseor_created_by_id_2ea025f3_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_purchaseorder
    ADD CONSTRAINT suppliers_purchaseor_created_by_id_2ea025f3_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suppliers_purchaseorderitem suppliers_purchaseor_order_id_f3ccb97e_fk_suppliers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_purchaseorderitem
    ADD CONSTRAINT suppliers_purchaseor_order_id_f3ccb97e_fk_suppliers FOREIGN KEY (order_id) REFERENCES public.suppliers_purchaseorder(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suppliers_purchaseorderitem suppliers_purchaseor_product_id_14c4e768_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_purchaseorderitem
    ADD CONSTRAINT suppliers_purchaseor_product_id_14c4e768_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suppliers_purchaseorder suppliers_purchaseor_supplier_id_398b3921_fk_suppliers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_purchaseorder
    ADD CONSTRAINT suppliers_purchaseor_supplier_id_398b3921_fk_suppliers FOREIGN KEY (supplier_id) REFERENCES public.suppliers_supplier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suppliers_supplierproduct suppliers_supplierpr_product_id_dde39474_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_supplierproduct
    ADD CONSTRAINT suppliers_supplierpr_product_id_dde39474_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: suppliers_supplierproduct suppliers_supplierpr_supplier_id_160dc6f9_fk_suppliers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.suppliers_supplierproduct
    ADD CONSTRAINT suppliers_supplierpr_supplier_id_160dc6f9_fk_suppliers FOREIGN KEY (supplier_id) REFERENCES public.suppliers_supplier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict for7V66p12dDZPXMbGmZFAh06NvewWOkehOcCgkkTupz4O6rlXxuSmFFy4Gyckd

