# Generated by Django 6.0.3 on 2026-03-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación física (pasillo-estante-nivel)', max_length=100),
        ),
    ]
