# Generated by Django 6.0.3 on 2026-03-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: heroicons)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='% IVA', max_digits=5)),
                ('unit', models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('mt', 'Metro'), ('box', 'Caja'), ('pack', 'Paquete')], default='unit', max_length=10)),
                ('min_stock', models.PositiveIntegerField(default=10)),
                ('max_stock', models.PositiveIntegerField(default=1000)),
                ('reorder_point', models.PositiveIntegerField(default=20)),
                ('reorder_quantity', models.PositiveIntegerField(default=50)),
                ('has_batches', models.BooleanField(default=False, help_text='¿Maneja lotes y fechas de vencimiento?')),
                ('has_serial_numbers', models.BooleanField(default=False, help_text='¿Maneja números de serie?')),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO - Primero en entrar, primero en salir'), ('lifo', 'LIFO - Último en entrar, primero en salir'), ('avg', 'Costo promedio ponderado')], default='avg', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendido'), ('reserved', 'Reservado'), ('damaged', 'Dañado')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='products.product')),
            ],
            options={
                'verbose_name': 'Número de serie',
                'verbose_name_plural': 'Números de serie',
            },
        ),
    ]
